services:
  db:
    image: postgres:15-alpine
    container_name: horus-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-horus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-horuspassword}
      POSTGRES_DB: ${POSTGRES_DB:-horuscrm}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-horus} -d ${POSTGRES_DB:-horuscrm}"]
      interval: 5s
      timeout: 5s
      retries: 12

  backend:
    build:
      context: ./backend
    container_name: horus-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-horus}:${POSTGRES_PASSWORD:-horuspassword}@db:5432/${POSTGRES_DB:-horuscrm}?schema=public
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-horus_super_secret_key_2026}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY:-BFvKHN15VTsqkPFNmIy13bcAIziXgf_H4ZaEngFBml3mBSXC-Vy7-NR79lv1JwW0slcKYlERjnOZgPsHnXfd94w}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY:-6_Qirt-gYtl5NxHLC_ofY19Dwc1-YYZXtqctMSK-3PM}
      - WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN:-mi_token_secreto_horustech}
      - DEFAULT_PHONE_NUMBER_ID=${DEFAULT_PHONE_NUMBER_ID:-}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@horustech.com}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-horustech2026}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:4001}
    ports:
      - "4001:3001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
    command: sh -c "until npx prisma db push >/dev/null 2>&1; do echo 'DB not ready, retrying...'; sleep 3; done; npm run seed || true; npm start"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4001}
    container_name: horus-frontend
    restart: always
    ports:
      - "4000:3002"
    depends_on:
      - backend

volumes:
  pgdata:
  uploads:
